### ISSUE TITLE
How does the Ember.computed.indirect initializer work?

### ISSUE THREAD

**Issue by gnarf** [gordonkristan/ember-computed-indirect#5]
It would seem to me that since most of your usage of `Ember.computed.indirect` would come from `App.SomethingComponent = Ember.Component.extend({ prop: Ember.computed.indirect })` type calls, however the way you are [currently adding `Ember.computed.indirect`](https://github.com/gordonkristan/ember-computed-indirect/blob/09e0313678a1882cbb9a7ef6c6e528199a009ddb/app/initializers/indirect.js#L6) won't happen until the app is first initialized.

How would you get access to it on the "global" computed during "assembly" of the application instead of extending object classes after the app has been created at runtime?

I think you should either just remove this, or find some way to add it during the "include phase", like adding something like this to the `index.js`

``` js
import Ember from 'ember';
import computedIndirect from 'ember-computed-indirect/utils/indirect';
Ember.computed.indrect = computedIndirect;

module.exports = {
  name: 'ember-computed-indirect'
};
```

so that when ember-cli "includes" your addon it extends the `Ember.computed` then instead.

Happy to PR if you want.

**Comment by gnarf** [comment]
I suppose another option would be to use the `included` callback method http://www.ember-cli.com/extending/#addon-entry-point

**Comment by gordonkristan** [comment]
I actually never really liked what I did there, I only put it there for consistency. (And you're right, I don't even think it works the way I imagined.) I'm just going to remove it.
