### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by dgaus** [gordonkristan/ember-computed-indirect#6]
Hi, now that the 1.12 syntax is supported, would you consider making a new release for npm? We are aiming to upgrade to Ember 2.0 soon and this is one of the few deprecation warnings left. Thanks!

**Comment by gordonkristan** [comment]
My apologies, I thought I did this. I'll take care of it now. :+1:

**Comment by gordonkristan** [comment]
Taken care of. Let me know if you run into any issues when upgrading to Ember 2.0.

**Comment by dgaus** [comment]
Awesome, thanks! cheers
